import {
  LayoutDashboard,
  Calendar,
  Users,
  MessageSquare,
  HeartPulse,
  Pill,
  Activity,
  Bell,
  CalendarOff,
  History,
  ClipboardList,
  FileText,
  UserCircle,
  PackageOpen,
  Truck,
  ShieldCheck,
  Soup,
  BarChart3,
  Droplets,
  Brain,
  Apple,
  Dumbbell,
} from 'lucide-react';

export const roleSidebarData = {
  doctor: [
    { title: 'sidebar.doctorDashboard', icon: LayoutDashboard, path: '/doctor/dashboard' },
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/doctor/profile' },
    { title: 'sidebar.myShifts', icon: Calendar, path: '/doctor/my-shifts' },
    { title: 'sidebar.careTasks', icon: ClipboardList, path: '/doctor/care-tasks' },
    { title: 'sidebar.appointments', icon: Calendar, path: '/doctor/appointments' },
    { title: 'sidebar.healthMonitoring', icon: HeartPulse, path: '/doctor/health-monitoring' },
    { title: 'sidebar.medication', icon: Pill, path: '/doctor/medications' },
    { title: 'sidebar.admissionRequests', icon: ClipboardList, path: '/doctor/admission-requests' },
    { title: 'sidebar.servicePackages', icon: HeartPulse, path: '/doctor/service-packages' },
    { title: 'sidebar.incidents', icon: FileText, path: '/doctor/incidents' },
    { title: 'sidebar.staffLeave', icon: CalendarOff, path: '/doctor/leave' },
    { title: 'sidebar.messages', icon: MessageSquare, path: '/doctor/messages' },
  ],
  caregiver: [

    {
      title: 'Dashboard Caregiver',
      icon: LayoutDashboard,
      path: '/caregiver/dashboard',
    },
    {
      title: 'Hồ sơ cá nhân',
      icon: UserCircle,
      path: '/caregiver/profile',
    },
    {
      title: 'sidebar.assignedResidents',
      icon: Users,
      path: '/caregiver/assigned-residents',
    },
    {
      title: 'sidebar.myShifts',
      icon: Calendar,
      path: '/caregiver/my-shifts',
    },
    {
      title: 'sidebar.staffLeave',
      icon: CalendarOff,
      path: '/caregiver/leave',
    },
    {
      title: 'sidebar.dailyCareSchedule',
      icon: ClipboardList,
      path: '/caregiver/daily-care-schedule',
    },
    {
      title: 'sidebar.mealIntakeNotes',
      icon: Soup,
      path: '/caregiver/meal-intake-notes',
    },
    {
      title: 'sidebar.dietPlans',
      icon: Apple,
      path: '/caregiver/diet-plans',
    },
    {
      title: 'sidebar.rehabSchedule',
      icon: Dumbbell,
      path: '/caregiver/rehabilitation-schedule',
    },
    {
      title: 'sidebar.hygieneActivities',

      icon: Droplets,
      path: '/caregiver/hygiene-activities',
    },
    {
      title: 'sidebar.dailyBehaviors',
      icon: Brain,
      path: '/caregiver/daily-behaviors',
    },
  ],
  nurse: [
    { title: 'sidebar.nurseDashboard', icon: LayoutDashboard, path: '/nurse/dashboard' },
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/nurse/profile' },
    { title: 'sidebar.myShifts', icon: Calendar, path: '/nurse/my-shifts' },
    { title: 'sidebar.careTasks', icon: ClipboardList, path: '/nurse/care-tasks' },
    { title: 'sidebar.activitySchedule', icon: Calendar, path: '/nurse/activity-schedule' },
    { title: 'sidebar.careNotes', icon: Activity, path: '/nurse/care-notes' },
    { title: 'sidebar.healthMonitoring', icon: HeartPulse, path: '/nurse/health-monitoring' },
    { title: 'sidebar.mealPlans', icon: Soup, path: '/nurse/meal-plans' },
    { title: 'sidebar.nutritionReports', icon: BarChart3, path: '/nurse/nutrition-reports' },
    { title: 'sidebar.medication', icon: Pill, path: '/nurse/medications' },
    { title: 'sidebar.admissionRequests', icon: ClipboardList, path: '/nurse/admission-requests' },
    { title: 'sidebar.servicePackages', icon: HeartPulse, path: '/nurse/service-packages' },
    { title: 'sidebar.incidents', icon: FileText, path: '/nurse/incidents' },
    { title: 'sidebar.staffLeave', icon: CalendarOff, path: '/nurse/leave' },
    { title: 'sidebar.messages', icon: MessageSquare, path: '/nurse/messages' },
  ],
  family: [
    { title: 'sidebar.familyDashboard', icon: LayoutDashboard, path: '/family/dashboard' },
    { title: 'sidebar.admissionHistory', icon: History, path: '/family/admission-requests' },
    { title: 'sidebar.facilityTourHistory', icon: Calendar, path: '/family/facility-tours' },
    { title: 'sidebar.activities', icon: Activity, path: '/family/activities' },
    { title: 'sidebar.residentInfo', icon: Users, path: '/family/resident' },
    { title: 'sidebar.notifications', icon: Bell, path: '/family/notifications' },
    { title: 'sidebar.messages', icon: MessageSquare, path: '/family/messages' },
  ],
  pharmacist: [
    { title: 'sidebar.pharmacyOverview', icon: LayoutDashboard, path: '/pharmacist/overview' },
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/pharmacist/profile' },
    { title: 'sidebar.medication', icon: Pill, path: '/pharmacist/medications' },
    { title: 'sidebar.pharmacySuppliers', icon: Truck, path: '/pharmacist/suppliers' },
    { title: 'sidebar.pharmacyStocks', icon: PackageOpen, path: '/pharmacist/stocks' },
    { title: 'sidebar.pharmacyDispense', icon: ShieldCheck, path: '/pharmacist/dispense' },
    { title: 'sidebar.pharmacyReports', icon: FileText, path: '/pharmacist/reports' },
  ],
};
