import {
  LayoutDashboard,
  Calendar,
  Users,
  MessageSquare,
  HeartPulse,
  Pill,
  Activity,
  Bell,
  CalendarOff,
  History,
  ClipboardList,
  FileText,
  UserCircle,
  PackageOpen,
  Truck,
  ShieldCheck,
  Soup,
  Droplets,
  Brain,
  Apple,
  Dumbbell,
  Image,
  LifeBuoy,
  CalendarDays,
} from 'lucide-react';

export const roleSidebarData = {
  doctor: [
    { title: 'sidebar.doctorDashboard', icon: LayoutDashboard, path: '/doctor/dashboard' },
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/doctor/profile' },
    { title: 'sidebar.myShifts', icon: Calendar, path: '/doctor/my-shifts' },
    { title: 'sidebar.assignedResidents', icon: Users, path: '/doctor/assigned-residents' },
    { title: 'sidebar.careTasks', icon: ClipboardList, path: '/doctor/care-tasks' },
    { title: 'sidebar.appointments', icon: Calendar, path: '/doctor/appointments' },
    { title: 'sidebar.mySchedule', icon: CalendarDays, path: '/doctor/schedule' },
    { title: 'sidebar.activitySchedule', icon: Calendar, path: '/doctor/activity-schedule' },
    { title: 'sidebar.healthMonitoring', icon: HeartPulse, path: '/doctor/health-monitoring' },
    { title: 'sidebar.initialHealthRecord', icon: FileText, path: '/doctor/residents/initial-health' },
    { title: 'sidebar.drugAllergies', icon: ShieldCheck, path: '/doctor/residents/drug-allergies' },
    { title: 'sidebar.medication', icon: Pill, path: '/doctor/medications' },
    { title: 'sidebar.admissionRequests', icon: ClipboardList, path: '/doctor/admission-requests' },
    { title: 'sidebar.servicePackages', icon: HeartPulse, path: '/doctor/service-packages' },
    { title: 'sidebar.incidents', icon: FileText, path: '/doctor/incidents' },
    { title: 'sidebar.staffLeave', icon: CalendarOff, path: '/doctor/leave' },
    { title: 'sidebar.notifications', icon: Bell, path: '/doctor/notifications' },
    { title: 'sidebar.messages', icon: MessageSquare, path: '/doctor/messages' },
  ],
  caregiver: [

    {
      title: 'Dashboard Caregiver',
      icon: LayoutDashboard,
      path: '/caregiver/dashboard',
    },
    {
      title: 'sidebar.myProfile',
      icon: UserCircle,
      path: '/caregiver/profile',
    },
    {
      title: 'sidebar.assignedResidents',
      icon: Users,
      path: '/caregiver/assigned-residents',
    },
    {
      title: 'sidebar.myShifts',
      icon: Calendar,
      path: '/caregiver/my-shifts',
    },
    {
      title: 'sidebar.staffLeave',
      icon: CalendarOff,
      path: '/caregiver/leave',
    },
    {
      title: 'sidebar.dailyCareSchedule',
      icon: ClipboardList,
      path: '/caregiver/daily-care-schedule',
    },
    {
      title: 'sidebar.activitySchedule',
      icon: Calendar,
      path: '/caregiver/activity-schedule',
    },
    {
      title: 'sidebar.mealIntakeNotes',
      icon: Soup,
      path: '/caregiver/meal-intake-notes',
    },
    {
      title: 'sidebar.dietPlans',
      icon: Apple,
      path: '/caregiver/diet-plans',
    },

    {
      title: 'sidebar.residentPhotos',
      icon: Image,
      path: '/caregiver/resident-photos',
    },
    {
      title: 'sidebar.hygieneActivities',
      icon: Droplets,
      path: '/caregiver/hygiene-activities',
    },
    {
      title: 'sidebar.dailyBehaviors',
      icon: Brain,
      path: '/caregiver/daily-behaviors',
    },
    {
      title: 'sidebar.messages',
      icon: MessageSquare,
      path: '/caregiver/messages',
    },
    {
      title: 'sidebar.notifications',
      icon: Bell,
      path: '/caregiver/notifications',
    },
    {
      title: 'sidebar.incidents',
      icon: FileText,
      path: '/caregiver/incidents',
    },
  ],

  nurse: [
    { title: 'sidebar.nurseDashboard', icon: LayoutDashboard, path: '/nurse/dashboard' },
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/nurse/profile' },
    { title: 'sidebar.myShifts', icon: Calendar, path: '/nurse/my-shifts' },
    { title: 'sidebar.assignedResidents', icon: Users, path: '/nurse/assigned-residents' },
    { title: 'sidebar.careTasks', icon: ClipboardList, path: '/nurse/care-tasks' },
    { title: 'sidebar.activitySchedule', icon: Calendar, path: '/nurse/activity-schedule' },
    { title: 'sidebar.appointments', icon: Calendar, path: '/nurse/appointments' },
    { title: 'sidebar.careNotes', icon: Activity, path: '/nurse/care-notes' },
    { title: 'sidebar.healthMonitoring', icon: HeartPulse, path: '/nurse/health-monitoring' },
    { title: 'sidebar.initialHealthRecord', icon: FileText, path: '/nurse/residents/initial-health' },
    { title: 'sidebar.mealPlans', icon: Soup, path: '/nurse/meal-plans' },
    { title: 'sidebar.medication', icon: Pill, path: '/nurse/medications' },
    { title: 'sidebar.admissionRequests', icon: ClipboardList, path: '/nurse/admission-requests' },
    { title: 'sidebar.residentVisitRequests', icon: Calendar, path: '/nurse/resident-visits' },
    { title: 'sidebar.servicePackages', icon: HeartPulse, path: '/nurse/service-packages' },
    { title: 'sidebar.incidents', icon: FileText, path: '/nurse/incidents' },
    { title: 'sidebar.staffLeave', icon: CalendarOff, path: '/nurse/leave' },
    { title: 'sidebar.notifications', icon: Bell, path: '/nurse/notifications' },
    { title: 'sidebar.messages', icon: MessageSquare, path: '/nurse/messages' },
  ],

  family: [
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/family/profile' },
    { title: 'sidebar.familyDashboard', icon: LayoutDashboard, path: '/family/dashboard' },
    { title: 'sidebar.admissionHistory', icon: History, path: '/family/admission-requests' },
    { title: 'sidebar.facilityTourHistory', icon: Calendar, path: '/family/facility-tours' },
    { title: 'sidebar.residentVisits', icon: Calendar, path: '/family/resident-visits' },
    { title: 'sidebar.residentPhotos', icon: Image, path: '/family/resident-photos' },
    { title: 'sidebar.residentAppointments', icon: CalendarDays, path: '/family/appointments' },
    { title: 'sidebar.activities', icon: Activity, path: '/family/activities' },
    { title: 'sidebar.residentInfo', icon: Users, path: '/family/resident' },
    { title: 'sidebar.notifications', icon: Bell, path: '/family/notifications' },
    { title: 'sidebar.messages', icon: MessageSquare, path: '/family/messages' },
    { title: 'sidebar.supportRequests', icon: LifeBuoy, path: '/family/support-requests' },
  ],

  pharmacist: [
    { title: 'sidebar.pharmacyOverview', icon: LayoutDashboard, path: '/pharmacist/overview' },
    { title: 'sidebar.myShifts', icon: Calendar, path: '/pharmacist/my-shifts' },
    { title: 'sidebar.staffLeave', icon: CalendarOff, path: '/pharmacist/leave' },
    { title: 'sidebar.myProfile', icon: UserCircle, path: '/pharmacist/profile' },
    { title: 'sidebar.medication', icon: Pill, path: '/pharmacist/medications' },
    { title: 'sidebar.pharmacySuppliers', icon: Truck, path: '/pharmacist/suppliers' },
    { title: 'sidebar.pharmacyStocks', icon: PackageOpen, path: '/pharmacist/stocks' },
    { title: 'sidebar.incidents', icon: FileText, path: '/pharmacist/incidents' },
    { title: 'sidebar.pharmacyReports', icon: FileText, path: '/pharmacist/reports' },
  ],
};
