import {
  LayoutDashboard,
  Users,
  Building2,
  Calendar,
  Activity,
  FileText,
  Bell,
  Shield,
  HeartPulse,
  Pill,
  ClipboardList,
  MessageSquare,
  LifeBuoy,
  Settings,
  FileCheck,
  DollarSign,
  UserCircle,
  ScrollText,
  UserPlus,
  MapPin,
  Compass,
  Package,
  Heart,
  Layers,
  BedDouble,
  DoorOpen,
  Briefcase,
  Clock,
  UserCog,
  AlertTriangle as AlertTriangleIcon,
  CalendarClock,
  BarChart3,
  Trophy,
  Stethoscope,
  Receipt,
} from 'lucide-react';

export const sidebarData = [
  {
    title: 'sidebar.dashboard',
    icon: LayoutDashboard,
    path: '/admin/dashboard',
  },
  {
    title: 'sidebar.authentication',
    icon: Shield,
    children: [
      { title: 'sidebar.myProfile', icon: UserCircle, path: '/admin/profile' },
      { title: 'sidebar.auditLogs', icon: ScrollText, path: '/admin/audit-logs' },
    ],
  },
  {
    title: 'sidebar.residents',
    icon: Users,
    children: [
      { title: 'sidebar.residents', icon: Users, path: '/admin/residents' },
      { title: 'sidebar.familyInfo', icon: Heart, path: '/admin/residents/family' },
      { title: 'sidebar.residentsByArea', icon: MapPin, path: '/admin/residents/by-area' },
      { title: 'sidebar.initialHealth', icon: HeartPulse, path: '/admin/residents/initial-health' },
      { title: 'sidebar.preExistingConditions', icon: FileText, path: '/admin/residents/pre-existing-conditions' },
      { title: 'sidebar.drugAllergies', icon: Pill, path: '/admin/residents/drug-allergies' },
      { title: 'sidebar.transferResident', icon: DoorOpen, path: '/admin/residents/transfer-room' },
    ],
  },
  {
    title: 'sidebar.admissionManagement',
    icon: ClipboardList,
    children: [
      { title: 'sidebar.admissionRequests', icon: UserPlus, path: '/admin/admission-requests' },
      { title: 'sidebar.tourRequests', icon: Compass, path: '/admin/tour-requests' },
      { title: 'sidebar.residentVisitRequests', icon: Calendar, path: '/admin/resident-visits' },
      { title: 'sidebar.servicePackages', icon: Package, path: '/admin/service-packages' },
    ],
  },
  {
    title: 'sidebar.buildingsFacilities',
    icon: Building2,
    children: [
      { title: 'sidebar.buildings', icon: Building2, path: '/admin/buildings' },
      { title: 'sidebar.floors', icon: Layers, path: '/admin/floors' },
      { title: 'sidebar.rooms', icon: DoorOpen, path: '/admin/rooms' },
      { title: 'sidebar.beds', icon: BedDouble, path: '/admin/beds' },
    ],
  },
  {
    title: 'sidebar.staffManagement',
    icon: Briefcase,
    children: [
      { title: 'sidebar.staffProfiles', icon: UserCog, path: '/admin/staff/profiles' },
      { title: 'sidebar.shifts', icon: Clock, path: '/admin/staff/shifts' },
      { title: 'sidebar.assignments', icon: MapPin, path: '/admin/staff/assignments' },
      { title: 'sidebar.emergencyAvailability', icon: AlertTriangleIcon, path: '/admin/staff/emergency' },
      { title: 'sidebar.leaveRequests', icon: CalendarClock, path: '/admin/staff/leave-requests' },
    ],
  },
  {
    title: 'sidebar.activities',
    icon: Activity,
    children: [
      { title: 'sidebar.activityManagement', icon: Activity, path: '/admin/activities' },
      { title: 'sidebar.activityStatistics', icon: BarChart3, path: '/admin/activities/statistics' },
      { title: 'sidebar.participationResults', icon: Trophy, path: '/admin/activities/participation-results' },
    ],
  },
  {
    title: 'sidebar.clinical',
    icon: HeartPulse,
    children: [
      { title: 'sidebar.clinicalServices', icon: Stethoscope, path: '/admin/services' },
      { title: 'sidebar.medicalCharges', icon: Receipt, path: '/admin/medical-charges' },
    ],
  },
  {
    title: 'sidebar.medication',
    icon: Pill,
    path: '/admin/medications',
  },
  {
    title: 'sidebar.appointments',
    icon: Calendar,
    path: '/admin/appointments',
  },
  {
    title: 'sidebar.incidents',
    icon: AlertTriangleIcon,
    path: '/admin/incidents',
  },
  {
    title: 'sidebar.reports',
    icon: BarChart3,
    path: '/admin/reports',
  },
  {
    title: 'sidebar.contractManagement',
    icon: FileCheck,
    path: '/admin/contracts',
  },
  {
    title: 'sidebar.billing',
    icon: DollarSign,
    path: '/admin/invoices',
  },
  {
    title: 'sidebar.notifications',
    icon: Bell,
    path: '/admin/notifications',
  },
  {
    title: 'sidebar.communication',
    icon: MessageSquare,
    path: '/admin/messages',
  },
  {
    title: 'sidebar.supportRequests',
    icon: LifeBuoy,
    path: '/admin/support-requests',
  },
  {
    title: 'sidebar.settings',
    icon: Settings,
    path: '/admin/settings',
  },
];